### ISSUE TITLE
expressive 3 preview: try install zend-expressive-authentication-session:^1.0.0-dev got error reference of http-interop/http-middleware 0.4.1

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-expressive-authentication-session#4]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-authentication-session/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-authentication-session/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```bash
composer require zendframework/zend-expressive-authentication-session:^1.0.0-dev
```

### Expected results

Working

### Actual results

```
Problem 1
    - Installation request for zendframework/zend-expressive-authentication-session ^1.0.0-dev -> satisfiable by zendframework/zend-expressive-authentication-session[1.0.x-dev].
    - zendframework/zend-expressive-authentication-session 1.0.x-dev requires zendframework/zend-expressive-session ^0.1.0 -> satisfiable by zendframework/zend-expressive-session[0.1.0, 0.1.x-dev].
    - zendframework/zend-expressive-session 0.1.0 requires http-interop/http-middleware ^0.4.1 -> satisfiable by http-interop/http-middleware[0.4.1].
    - zendframework/zend-expressive-session 0.1.x-dev requires http-interop/http-middleware ^0.4.1 -> satisfiable by http-interop/http-middleware[0.4.1].
    - Conclusion: don't install http-interop/http-middleware 0.4.1
```

**Comment by geerteltink** [comment]
Looks like the composer file isn't updated yet: https://github.com/zendframework/zend-expressive-authentication-session/blob/master/composer.json#L25

It should depend on `"zendframework/zend-expressive-session": "^1.0.0-dev"`.
